// Тестовые данные товаров для Pideh Armenia
import { Product } from '@prisma/client'

export const sampleProducts: Omit<Product, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Классическая Хачапури',
    description: 'Традиционная аджарская хачапури с сыром сулугуни и яйцом',
    price: 2500,
    image: '/images/classic-khachapuri.jpg',
    category: 'Классические',
    ingredients: ['Тесто', 'Сыр сулугуни', 'Яйцо', 'Масло', 'Соль'],
    isAvailable: true,
  },
  {
    name: 'Мясная Хачапури',
    description: 'Хачапури с говядиной, луком и специями',
    price: 3200,
    image: '/images/meat-khachapuri.jpg',
    category: 'Мясные',
    ingredients: ['Тесто', 'Говядина', 'Лук', 'Сыр', 'Специи'],
    isAvailable: true,
  },
  {
    name: 'Сырная Хачапури',
    description: 'Смесь сыров: сулугуни, моцарелла и чеддер',
    price: 2800,
    image: '/images/cheese-khachapuri.jpg',
    category: 'Сырные',
    ingredients: ['Тесто', 'Сулугуни', 'Моцарелла', 'Чеддер', 'Масло'],
    isAvailable: true,
  },
  {
    name: 'Овощная Хачапури',
    description: 'Свежие овощи: помидоры, перец, лук, зелень',
    price: 2200,
    image: '/images/vegetable-khachapuri.jpg',
    category: 'Овощные',
    ingredients: ['Тесто', 'Помидоры', 'Перец', 'Лук', 'Зелень', 'Сыр'],
    isAvailable: true,
  },
  {
    name: 'Грибная Хачапури',
    description: 'Шампиньоны с луком и сливочным соусом',
    price: 2600,
    image: '/images/mushroom-khachapuri.jpg',
    category: 'Грибные',
    ingredients: ['Тесто', 'Шампиньоны', 'Лук', 'Сливки', 'Сыр', 'Зелень'],
    isAvailable: true,
  },
  {
    name: 'Острая Хачапури',
    description: 'С острым перцем, чесноком и специями',
    price: 2400,
    image: '/images/spicy-khachapuri.jpg',
    category: 'Острые',
    ingredients: ['Тесто', 'Острый перец', 'Чеснок', 'Сыр', 'Специи'],
    isAvailable: true,
  },
  {
    name: 'Морепродукты Хачапури',
    description: 'Креветки и кальмары с чесноком',
    price: 3800,
    image: '/images/seafood-khachapuri.jpg',
    category: 'Морепродукты',
    ingredients: ['Тесто', 'Креветки', 'Кальмары', 'Чеснок', 'Лимон', 'Сыр'],
    isAvailable: true,
  },
  {
    name: 'Детская Хачапури',
    description: 'Нежная хачапури без острых специй',
    price: 2000,
    image: '/images/kids-khachapuri.jpg',
    category: 'Детские',
    ingredients: ['Тесто', 'Сыр', 'Масло', 'Соль'],
    isAvailable: true,
  },
  {
    name: 'Веганская Хачапури',
    description: 'Без молочных продуктов, с растительным сыром',
    price: 2300,
    image: '/images/vegan-khachapuri.jpg',
    category: 'Веганские',
    ingredients: ['Тесто', 'Растительный сыр', 'Овощи', 'Зелень'],
    isAvailable: true,
  },
  {
    name: 'Сладкая Хачапури',
    description: 'С творогом, изюмом и медом',
    price: 2100,
    image: '/images/sweet-khachapuri.jpg',
    category: 'Сладкие',
    ingredients: ['Тесто', 'Творог', 'Изюм', 'Мед', 'Корица'],
    isAvailable: true,
  },
]

export const categories = [
  'Все',
  'Классические',
  'Мясные',
  'Сырные',
  'Овощные',
  'Грибные',
  'Острые',
  'Морепродукты',
  'Детские',
  'Веганские',
  'Сладкие',
] as const

export type Category = typeof categories[number]
